### ISSUE TITLE
在vivo手机上不能显示

### ISSUE THREAD

**Issue by doumengnan** [Jon-Millent/mi-shop#1]
在vivo手机上显示为空白页，锤子手机没问题

**Comment by Jon-Millent** [comment]
你好，你的手机的安卓版本是多少？用的是哪一个浏览器？请具体说一下。😀

**Comment by doumengnan** [comment]
vivo是4.4.2，使用了babel-polyfill也不可以，在锤子手机上安卓版本6.0.1显示正常

**Comment by Jon-Millent** [comment]
vue2.0 对低版本的安卓支持不太好，具体我也没有太好的建议，具体参考下面。
http://blog.csdn.net/qq_16559905/article/details/70238583
https://github.com/vuejs/vue-hackernews-2.0/issues/33
https://github.com/vuejs/vue/issues/5623
