### ISSUE TITLE
 ERROR  Failed to compile with 16 errors

### ISSUE THREAD

**Issue by MrPei2** [Jon-Millent/mi-shop#2]
These dependencies were not found:

* babel-runtime/core-js/json/stringify in ./src/util/shop-car-tool/index.js, ./src/util/vue-db/vue-db.js and 1 other
* babel-runtime/helpers/classCallCheck in ./src/assets/js/rem.js, ./src/util/shop-car-tool/index.js and 2 others
* babel-runtime/helpers/createClass in ./src/assets/js/rem.js, ./src/util/shop-car-tool/index.js and 2 others * babel-runtime/helpers/extends in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/detail/index.vue
* babel-runtime/helpers/typeof in ./src/assets/swiper/swiper-3.4.2.min.js, ./src/util/vue-db/vue-db-long.js and 1 other

**Comment by Jon-Millent** [comment]
重新克隆一份项目，尝试用 `cnpm install` 或者 `yarn`   安装依赖
Re-clon a project and try installing dependencies with `cnpm install` or `yarn`
