### ISSUE TITLE
$npm install报错

### ISSUE THREAD

**Issue by dddw001** [Jon-Millent/mi-shop#3]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (H:\gitLocal\vue\mi-shop\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (H:\gitLocal\vue\mi-shop\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at H:\gitLocal\vue\mi-shop\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "H:\\procedure\\node\\install\\node.exe" "H:\\gitLocal\\vue\\mi-shop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd H:\gitLocal\vue\mi-shop\node_modules\node-sass
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Jon-Millent** [comment]
初步判断判断是node-sass模块的兼容问题， 解决参考 https://blog.csdn.net/notejs/article/details/49681517

**Comment by dddw001** [comment]
你这个写了后端代码？

**Comment by Jon-Millent** [comment]
没有后台代码，问题解决了么？🍄

**Comment by dddw001** [comment]
网址为 http://0.0.0.0:8080/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_ADDRESS_INVALID
$npm run _dev之后是这样的
