### ISSUE TITLE
npm run dev 出现错误

### ISSUE THREAD

**Issue by zj2050** [Jon-Millent/mi-shop#7]
`
> mi-shop@1.0.0 dev /Users/liugrant/Documents/Tsingbegin/VueHealth
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 14% building modules 39/59 modules 20 active ...th/src/views/classification/index.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 94% asset optimization                                                       n         
 ERROR  Failed to compile with 2 errors                              下午1:12:46

 error  in ./src/views/detail/index.vue

Syntax Error: Unexpected token (110:4)

  108 |   },
  109 |   computed: {
> 110 |     ...mapGetters([
      |     ^
  111 |       'getShopCarLength'
  112 |     ])
  113 |   },

 @ ./src/views/detail/index.vue 8:0-108 9:0-121
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

 error  in ./src/App.vue

Syntax Error: Unexpected token (82:4)

  80 |   },
  81 |   computed: {
> 82 |     ...mapGetters([
     |     ^
  83 |       'nowStatus',
  84 |       'getShopCarLength'
  85 |     ]),

 @ ./src/App.vue 8:0-100 9:0-113
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js
`

**Comment by Jon-Millent** [comment]
你好，这个看起来是babel打包时候的问题，考虑到这个项目的构建是很久前的，我已经用cli3重新构建项目，请重新clone后再编译一下.
